### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by MariiaKravchuk** [MariiaKravchuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by MariiaCollaborator** [comment]
<h3>The most important events</h3>
<ul class="timeline">
<li>
<p><small>**May 12, 1956** </small></p>
<p>Homer Simpson is born.</p>
</li>
<li>
<p><small>**1966** </small></p>
<p>Homer and Marge kiss each other at night during summer camp, but they do not know it is them.</p>
</li>
<li>
<p><small>**July 20, 1969** </small></p>
<p>While everyone else is watching the moon landing, Homer has been sent to his room, where he is listening to the song "Yummy, Yummy, Yummy, I Got Love in My Tummy" by the Ohio Express.</p>
</li>
<li>
<p><small>**1976**</small></p>
<p>After Homer and Marge crash their bikes, newlyweds Ned and Maude pick them up. Later, they go to Kozy Kabins where Ned makes Homer and Marge live in separate rooms from each other because they are not yet married. The next day, Homer makes a carving into a tree that says Marge + Homer 4Ever. </p>
</li>
<li>
<p>small>**1980**</small></p>
<p>Homer Simpson and Marge Bouvier got married.</p>
</li>
<li>
<p><small>**1994**</small></p>
<p>Homer goes to outer space. </p>
</li>
<li>
<p><small>**1996**</small></p>
<p>Homer beats up former president George H. W. Bush.</p>
</li>
<li>
<p><small>**January 31, 1999**</small></p>
<p>Homer and a new friend, Wally Kogen, take several Springfield citizens to Super Bowl XXXIII in Miami. However, they are locked in a detention cell after their tickets are discovered to be counterfeit.</p>
</li>
<li>
<p><small>**August 2001**</small></p>
<p>Homer goes on a hunger strike to expose Howard K. Duff VIII’s plan to move the Springfield Isotopes to Albuquerque.</p>
</li>
<li>
<p><small>**2004**</small></p>
<p>Homer establishes a short-lived identity, Pie Man.</p>
</li>
<li>
<p><small>**Summer 2007**</small></p>
<p>Homer makes Springfield become the most polluted city in the history of the planet. Russ Cargill tries to make sure it does not spread. Homer takes his family with him to Alaska where they can start a new life. They find out that Russ Cargill is planning to blow up Springfield to start a second Grand Canyon. They go back to Springfield to save everyone.</p>
 </li>
</ul>
